// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvzh4Y-prTATLGwwuW0Fcji3U_s59exvQ',
    appId: '1:845708029735:web:66178b500e4e3904958302',
    messagingSenderId: '845708029735',
    projectId: 'laptopharbor-ac2d9',
    authDomain: 'laptopharbor-ac2d9.firebaseapp.com',
    storageBucket: 'laptopharbor-ac2d9.firebasestorage.app',
    measurementId: 'G-NP27J870YP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGo010_8M256c0-LIYWhi92zt9eDtltTk',
    appId: '1:845708029735:android:a57b970418eda47f958302',
    messagingSenderId: '845708029735',
    projectId: 'laptopharbor-ac2d9',
    storageBucket: 'laptopharbor-ac2d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV8P2WRYjVri5ZNyepfo1EZOkzJWOg_8Q',
    appId: '1:845708029735:ios:9723c6a993a44ab1958302',
    messagingSenderId: '845708029735',
    projectId: 'laptopharbor-ac2d9',
    storageBucket: 'laptopharbor-ac2d9.firebasestorage.app',
    iosBundleId: 'com.alishba.laptopharbor.laptopHarbor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV8P2WRYjVri5ZNyepfo1EZOkzJWOg_8Q',
    appId: '1:845708029735:ios:9723c6a993a44ab1958302',
    messagingSenderId: '845708029735',
    projectId: 'laptopharbor-ac2d9',
    storageBucket: 'laptopharbor-ac2d9.firebasestorage.app',
    iosBundleId: 'com.alishba.laptopharbor.laptopHarbor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvzh4Y-prTATLGwwuW0Fcji3U_s59exvQ',
    appId: '1:845708029735:web:8455c4818b1a821e958302',
    messagingSenderId: '845708029735',
    projectId: 'laptopharbor-ac2d9',
    authDomain: 'laptopharbor-ac2d9.firebaseapp.com',
    storageBucket: 'laptopharbor-ac2d9.firebasestorage.app',
    measurementId: 'G-8B42HFQLLK',
  );

}